### ISSUE TITLE
New user guilds not showing

### ISSUE THREAD

**Issue by tandpfun** [tonestrike/passport-discord#2]
Hi there!

I was using passport-discord to authenticate users on my web dashboard, but when they create a new guild, or join a server and are given admin, it doesn't show up on their server list until they log out and log in again. What should I do to make it show new guilds?

I currently get the guilds through the req.user.guilds list, and don't refresh anything.

Thanks,
Coding

**Comment by tonestrike** [comment]
@tandpfun that is a bit out of the context of this package, but you can check out the relevant documentation on getting a user's guilds [here](https://discord.com/developers/docs/resources/user).
